const joi = require('joi');
exports.schemaKeys = joi.object({
  appointmentId: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  patientId: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  providerId: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  diagnosis: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  allergies: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  pregnancyStatus: joi.boolean(),
  note: joi.string(),
  medication: joi.array(), 
  followupDate: joi.object(),
  treatmentIds: joi.array(),
  treatment: joi.array(),
  referTo: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  furtherInstructions: joi.string(),
  pharmacyId: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  treatmentInvoice: joi.string(),
  treatmentAmount: joi.number(),
  orderId: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  createdBy: joi.object(),
  updatedBy: joi.object(),
  isActive: joi.boolean().default(true),
  isDelete: joi.boolean().default(false),
  isDeleted: joi.boolean()
}).unknown(true);
exports.updateSchemaKeys = joi.object({
  appointmentId: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  patientId: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  providerId: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  diagnosis: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  allergies: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  pregnancyStatus: joi.boolean(),
  note: joi.string(),
  medication: joi.array(),
  followupDate: joi.object(),
  treatmentIds: joi.array(),
  treatment: joi.array(),
  referTo: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  furtherInstructions: joi.string(),
  pharmacyId: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  treatmentAmount: joi.number(),
  treatmentInvoice: joi.string(),
  orderId: joi.string().regex(/^[0-9a-fA-F]{24}$/),
  createdBy: joi.object(),
  updatedBy: joi.object(),
  isActive: joi.boolean().default(true),
  isDelete: joi.boolean().default(false),
  isDeleted: joi.boolean()
}).unknown(true);
