module.exports = {
  NOTIFICATION: {
    TYPE: {
      EMAIL: "EMAIL",
      SMS: "SMS",
      PUSH_NOTIFICATION: "PUSH_NOTIFICATION",
    },
    PUSH_NOTIFICATION_TYPE: {
      STATIC: "STATIC",
      DYNAMIC: "DYNAMIC",
    },
    STATUS: {
      SEND: "SEND",
      READ: "READ",
    },
    ACTIONS: {
      APPOINTMENT_PENDING: "APPOINTMENT_PENDING",
      APPOINTMENT_UPCOMING: "APPOINTMENT_UPCOMING",
      APPOINTMENT_COMPLETED: "APPOINTMENT_COMPLETED",
      APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
      VIDEO_CALL_REMINDER: "VIDEO_CALL_REMINDER",
      TRANSACTION_SUCCESS: "TRANSACTION_SUCCESS",
      PROFILE_DEACTIVATION: "PROFILE_DEACTIVATION",
      VIDEO_CALL_COMPLETED: "COMPLETED_CALL",
      LOGIN_SUCCCESSFUL: "LOGIN_SUCCCESSFUL",
      SERVICE_ADDED: "SERVICE_ADDED",
      SERVICE_UPDATED: "SERVICE_UPDATED",
      TREATMENT_ASSIGNED: "TREATMENT_ASSIGNED",
      PHYSICIAN_DEACTIVATED: "PHYSICIAN_DEACTIVATED",
      USER_UPDATED: "USER_UPDATED",
    },
  },
};
